### ISSUE TITLE
ValueError: Padding is incorrect.

### ISSUE THREAD

**Issue by boqxfjge** [ytyt-yt/anki-biaori#3]
不懂编程，因为分享的只有初级基本课文，想制作中级高级的内容，尝试使用这个，其他报错靠百度解决了，furigana也不知道该怎么修改，对应内容直接删了还可以另外找其他方式注音；但是下面这个错误不知道该怎么解决，可以帮帮忙吗。
Traceback (most recent call last):
  File "D:\Downloads\anki-biaori\biaori.py", line 129, in <module>
    main()
  File "D:\Downloads\anki-biaori\biaori.py", line 124, in main
    lst.extend(process_basic(1, (i-1) // 4 + 1, i, key))
  File "D:\Downloads\anki-biaori\biaori.py", line 74, in process_basic
    d = decrypt(basic_dat_fn, key)
  File "D:\Downloads\anki-biaori\biaori.py", line 20, in decrypt
    data = unpad(cipher.decrypt(data), AES.block_size)
  File "C:\Users\11019\AppData\Local\Programs\Python\Python38\lib\site-packages\Crypto\Util\Padding.py", line 92, in unpad
    raise ValueError("Padding is incorrect.")
ValueError: Padding is incorrect.

**Comment by ytyt-yt** [comment]
中高级试试把 120行改成 `"@@pepmres.com.cn"`

**Comment by ytyt-yt** [comment]
中高级课文段落比较长，感觉不太适合做卡片

**Comment by boqxfjge** [comment]
课文不是按句分的，而是按整个段落分的吗？
标日app里可以直接点击单句开始朗读，一些第三方app里也可以单句朗读，我以为它本身自带了时间轴呢。
我目前在中级，看前面的对话部分句子还好，只做这部分也行，但是我又出现了新的问题：
Traceback (most recent call last):
  File "D:\ffmpeg-2022-09-07-git-e4c1272711-full_build\bin\anki-biaori\biaori.py", line 130, in <module>
    main()
  File "D:\ffmpeg-2022-09-07-git-e4c1272711-full_build\bin\anki-biaori\biaori.py", line 125, in main
    lst.extend(process_basic(1, (i-1) // 4 + 1, i, key))
  File "D:\ffmpeg-2022-09-07-git-e4c1272711-full_build\bin\anki-biaori\biaori.py", line 82, in process_basic
    if c['content'] != '#' and not c['trans']:
KeyError: 'content'
我按网上教程安装了ffmpeg，也配置了环境变量，但是直接在命令窗口检查有没有安装上的时候，提示无法将“ffmpeg”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。直接在目录里检查的时候是正常的，于是我把标日这个整个复制到了ffmpeg，不知道有没有影响

**Comment by ytyt-yt** [comment]
这个出错应该是因为数据结构不太一样，这个得自己根据实际数据格式改
